### ISSUE TITLE
Workflow of testing other programs

### ISSUE THREAD

**Issue by jiezhoucs** [embedded-sec/uRAI#1]
It looks like the current instructions are customized for analyzing, compiling, and running the 6 programs in the paper. Could you give us the instructions to build the workflow for testing other programs (e.g., BEEBS)?

**Comment by nalmakhd** [comment]
Hi Jie,

Thanks for your interest.

I will be happy to do so and this is on my to-do list. That is, to provide a template to compile other apps. However these require porting to Clang or having a specific template per-each benchmark, and I will not be able to do so soon due to time constraints at the moment. The same goes for some features which I have disabled (e.g., optimizing how pre-compiled libraries are handled) that will need some extra work to stabilize that I cannot get to at the moment.

What might help is to look at the makefile template (https://github.com/embedded-sec/uRAI/blob/master/compiler/tools/build_tools/CubeMX2Makefile.tpl) between lines 153 & 237. You can port these to the other apps you are interested in. Though I would say BEEBS are too simple for an evaluation, many are just one or two simple functions, they just execute for long time because they are repeated N times. 

A simpler option might be to copy one of the existing apps, replace the main files with you application, and add any necessary files to the directory then try building it. Just make sure you add a symlink of the MPU configs as done here (https://github.com/embedded-sec/uRAI/blob/master/compiler/mpu_configs/setup_mpu_config_sym_links.sh).

Note that all these apps are for the STM32479-EVAL board, you might need to change things for you board also.

Hope this helps!
